### ISSUE TITLE
upgrade to go 1.11

### ISSUE THREAD

**Issue by KaiserKarel** [abdullin/cellar#3]
Seems that the library cannot simply be cloned and run, due dependencies changing. Maybe best to move to versioned dependency management

**Comment by abdullin** [comment]
Would you care to send a Pull Request?

I've personally used glide in the other projects. Not sure if it still is the mainstream approach, though.

**Comment by KaiserKarel** [comment]
I'll get on it.

**Comment by abdullin** [comment]
Thanks!

Merged #4 and enabled travis. It is running a build right now. If the fuzz test takes too much time, I'll shorten it later.

**Comment by KaiserKarel** [comment]
great, seems to be working fine. :)

**Comment by abdullin** [comment]
👍 thanks!
